### ISSUE TITLE
Depending on plugins 

### ISSUE THREAD

**Issue by imjack** [Nukkit/Nukkit#173]
Adding depend in the plugin.yml Doesn't seem to make much difference
23:21:20 [INFO] Enabling MadRegions v1.0.0
23:21:20 [INFO] [MadRegions] MadRegion is loading....
23:21:20 [INFO] Enabling MadPerms v1.0.0
23:21:20 [INFO] [MadPerms] MadPerms is loading....

In my MadRegions plugin.yml
```` yaml
name: MadRegions
main: me.imjack.region.Main
version: "1.0.0"
api: ["1.0.0"]
depend:
- MadPerms
````

**Comment by Snake1999** [comment]
@imjack Yes, no difference if both plugins are installed. But if MadPerms is required by MadRegions but is not installed, Nukkit will show that MadRegions can not use alone, and won't load it.

**Comment by MagicDroidX** [comment]
Try `loadbefore` for your purpose.

**Comment by imjack** [comment]
Thanks I'll try it when I'm on my computer next.

**Comment by fromgate** [comment]
I fixed it: https://github.com/fromgate/Nukkit/commit/de4e5f6aea384530866d8033628a7809fba2086c

**Comment by imjack** [comment]
I haven't tried @fromgate fix yet but using loadbefore Still doesn't work

````
14:39:22 [INFO] Enabling MadRegions v1.0.0
14:39:22 [INFO] [MadRegions] MadRegion is loading....
14:39:22 [INFO] Enabling MadPerms v1.0.0
14:39:22 [INFO] [MadPerms] MadPerms is loading....
````
MadPerms is using loadbefore

**Comment by fromgate** [comment]
I did not try loadbefore yet. But I can guess that my "fast-fix" (use LinkedHashMap instead of HashMap) will fix this issue too.

HashMap did not stores order of plugin loading. And plugins could be loaded in correct order but enabled in other order.

**Comment by imjack** [comment]
Well I'll have to wait until your pull request has been added as I'm having troubles building the jar.
