### ISSUE TITLE
Unable to connect to servers

### ISSUE THREAD

**Issue by ProjectInfinity** [Nukkit/Nukkit#199]
Noticed that connecting to external servers do not seem to work at all for me. I can connect locally just fine, but any other Nukkit server is a no go. 

What happens is that the client is stuck on "locating server" and then nothing happens on the console end of things. Never times out, nothing. Here's the only thing shown in console:

```
21:23:03 [NOTICE] Player data not found for "projectinfinity", creating new profile
21:23:03 [INFO] ProjectInfinity[/92.221.207.12:35585] logged in with entity id 2 at (world, 128.0, 0.0, 128.0)
```

Issue can be replicated on latest build (64) and 59. Both Windows and Linux.

**Comment by beetree** [comment]
Recreated on a fresh Ubuntu 14.04 installation.

Java:
```
# java -version
openjdk version "1.8.0_72-internal"
OpenJDK Runtime Environment (build 1.8.0_72-internal-b05)
OpenJDK 64-Bit Server VM (build 25.72-b05, mixed mode)
```

Log from starting server and joining from Android 0.13.1 client:
```
# java -jar nukkit.jar
22:02:33 [INFO] Welcome! Please choose a language first!
22:02:33 [INFO] eng => English
22:02:33 [INFO] chs => 中文（简体）
22:02:33 [INFO] cht => 中文（繁体）
22:02:33 [INFO] jpn => 日本語
22:02:33 [INFO] rus => Pyccĸий
> eng
22:02:34 [INFO] Loading nukkit.yml...
22:02:34 [INFO] Loading server properties...
22:02:34 [INFO] Selected English (eng) as the base language
22:02:34 [INFO] Starting Minecraft: PE server version v0.13.1 alpha
22:02:34 [INFO] Opening server on 0.0.0.0:19132
22:02:34 [INFO] This server is running Nukkit version 1.0dev "蘋果(Apple)派(Pie)" (API 1.0.0)
22:02:34 [INFO] Nukkit is distributed under the LGPL License
22:02:35 [NOTICE] Level "world" not found
22:02:35 [INFO] Preparing level "world"
22:02:35 [NOTICE] Spawn terrain for level "world" is being generated in the background
22:02:35 [INFO] Starting GS4 status listener
22:02:35 [INFO] Setting query port to 19132
22:02:35 [INFO] Query running on 0.0.0.0:19132
22:02:35 [INFO] Default game type: Survival Mode
22:02:35 [INFO] Done (2.253s)! For help, type "help" or "?"
22:04:18 [NOTICE] Player data not found for "beetree", creating new profile
22:04:18 [INFO] beetree[/204.11.229.35:42369] logged in with entity id 1 at (world, 128.0, 0.0, 128.0)
22:04:30 [INFO] beetree joined the game
>
```

The client is stuck in "Locating server" sometimes crashing the client completely. This happens on both iOS and Android.

Occassionally, the server with later on start working with clients being able of joining.

No error messages is ever displayed in the nukkit console.

**Comment by Pub4Game** [comment]
No, it deistvitelno problem Nukkit! Here is an example of incorrect creation of player profile #189

**Comment by ProjectInfinity** [comment]
What do you mean?

**Comment by beetree** [comment]
I'd be happy to provide login information to my test machine, or capture more logs from a custom version of Nukkit that prints more debug info.

Let me know how I can help...

**Comment by yungtechboy1** [comment]
Its just stuck on Building Terrain for me

**Comment by beetree** [comment]
Anything...?

**Comment by MagicDroidX** [comment]
Fixed here: https://github.com/Nukkit/Nukkit/commit/e869f8a86e04162cd01d174371cf74e24e23d31a

**Comment by beetree** [comment]
This fixed it for *most* clients. However, one of our Android devices still crashes and gets stuck in "Locating server". It's a Moto X fully upgraded 0.13.1 client.

**Comment by beetree** [comment]
Also, *sometimes* the following error is thrown. Not sure if it in any way gives a hint of the issue:

```
18:34:32 [ALERT] java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
        at java.util.HashMap$ValueIterator.next(HashMap.java:1458)
        at cn.nukkit.Server.forceShutdown(Server.java:677)
        at cn.nukkit.Server.start(Server.java:731)
        at cn.nukkit.Server.<init>(Server.java:427)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

18:34:32 [EMERGENCY] Exception happened while shutting down, exit the process
18:34:32 [EMERGENCY] RakNet crashed!
```

**Comment by ProjectInfinity** [comment]
Here's what it looked like on my end after trying to log in once he said he was stuck. I got further to this screen and it stopped at exactly that point.

![http://i.imgur.com/0AcRgbe.png](http://i.imgur.com/0AcRgbe.png)

**Comment by beetree** [comment]
Doing some more testing now and it seems that the Android client sometimes gets to "Locating server" sometimes it gets stuck on "Building terrain".

**Comment by beetree** [comment]
Two other data points:

The issue may be related to world generation. When starting up new servers with a pre-generated map, the issues are not happening as often. (this is obviously not client related)

It seems that parameters restricting java memory affects the prevalence of the issue as well. "-Xms32M -Xmx256M -XX:MaxPermSize=128M" generates the client crashes more often.

Real sorry about the uncorrelated pieces of information. I wish the issue would be more predictable. At this point it's a bit unclear whether it's client related or world-generation/memory related.

**Comment by beetree** [comment]
Still happens on the Android client even with pre-generated map and standard java params (java -jar nukkit.jar). When it happens, the server crashes (without any error) and no clients can join.
