### ISSUE TITLE
PC World Crash?

### ISSUE THREAD

**Issue by File14** [Nukkit/Nukkit#918]
### Issue description

Why can't I take a PC map and install on the Nukkit server? I crash everything I login to it.

### Steps to reproduce the issue

Install a PC world and try to join.

### OS and versions

* Nukkit: Build 1177
* OS: Windows 10
* Device: PC

### Crashdump, backtrace or other files
No Errors

**Comment by fromgate** [comment]
Because Minecraft PC and Minecraft Pocket Edition are different games.

**Comment by Pub4Game** [comment]
Just in 0.15.0 unknown blocks do a crash of the game. I hope this is corrected in the future, now you can edit the map using MCEdit and remove unknown blocks.

**Comment by Creeperface01** [comment]
no, itried to place some blocks from PC version and i see them like update block and without crash

**Comment by Creeperface01** [comment]
i made plugin, that removed all blocks and block entities that are not registered in nukkit. But still crashes

**Comment by File14** [comment]
Well, it has todo something with the blocks because I had a map, and it had EnderDragon eggs in it and once I removed them the client didn't crash anymore. @Creeperface01

**Comment by Snake1999** [comment]
I think the cause might be ID and meta that is different from PC and PE(#blamemojang). So do the conversation by yourself :)

**Comment by sero583** [comment]
@File14 As you said to me close your issue...
I've fixed that a long ago, well you need to write a world converter, which i did and voila it's working

**Comment by MagicDroidX** [comment]
LOL. The crash has existed since 0.9.0.

**Comment by sero583** [comment]
@MagicDroidX Nukkit is just doing its job, sending all the Blocks to MCPE and if the Block isn't contained in MCPE, Nukkit still sends it and thats causes a crash

**Comment by MrPowerGamerBR** [comment]
@MagicDroidX actually MCPE 0.14 removed the crash, but the crash came back in 0.15.

**Comment by sero583** [comment]
@MrPowerGamerBR Nvm that bug, if they want to use a pc map in nukkit they'll need to write a converter, i did it and it works fine, NON-PE Blocks gets replaced with the "Upd ate!" block in my plugin

**Comment by Creeperface01** [comment]
I have one too. But it works for almost every map. But some maps still crashes :/

**Comment by imjack** [comment]
@Creeperface01 Have you tried removing the entities in the chunk also?

**Comment by sero583** [comment]
@File14 You have twitter?

**Comment by File14** [comment]
@sero583 You can message me in Gitter's private chat!
